In [ ]:
cd static

/app/data/static

In [ ]:
ls

 Aurora_west/
 Aurora_west.zip
'Copy of eSchoolPlus to PowerSchool - Field mapping - 20180706.xlsx'
 Metrics_that_Matters.ipynb
 __MACOSX/
 esp_data_mod.xlsx
 final_df.csv
 samplenotebook.ipynb
 samplenotebook.qmd
 samplenotebook_files/
 source_table_names.csv
 stacked_df.csv

/usr/local/lib/python3.11/site-packages/lancedb/__init__.py:220: UserWarning: lance is not fork-safe. If you are using multiprocessing, use spawn instead.
  warnings.warn(

In [ ]:
from utils import *

In [ ]:
pd.read_excel('esp_data_mod.xlsx', sheet_name='Student')

    S.No  ...                                                                                                                                                                                                                                                                                                                                                                   Upload Considerations
0      1  ...                                                                                                                                                                                                          Unique identifier for the student\neSchoolPlus STUDENTID is type char(10), it is part of a compound primary key with "DISTRICT".\nCheck for alpha characters and leading zeros
1      2  ...                                                                                                                                                                                         SchoolID is used to ensure student is placed into the correct school in a district. (Must be used when importing students at the District level and must match a school number in PowerSchool.)
2      3  ...                                                                                                                                                                                                                                                                                                                                                               First Name of  student.
3      4  ...                                                                                                                                                                                                                                                                                                                                                                  Middle Name of student
4      5  ...                                                                                                                                                                                                                                                                                                                                                                   Last Name of  student
5      6  ...                                                                                                                                                         Grade level for the student.\n\nKindergarten=0 \nPK4 = -1\nPK3 = -2\nImports will accept -3 and -4 for grade levels lower than PK4 and PK3.\n\nuse the GRADE associated with entry and exit date used for the "STUDENTS" record
6      7  ...  Student's home phone number.  Should be formatted the same for all students in order for Family Management to use this field for matching.\n\nJoin REG > REG_STU_CONTACT (where CONTACT_TYPE = 'P' {physical address} > REG_CONTACT_PHONE (where PHONE_TYPE = Home {REGTB_PHON}\npossible multiple home phone records.  or client may want other phone types such as mobile cell phone
7      8  ...                                                                                                                                                                                                                                                                                                                                                Students gender.  Must be either M or F.
8      9  ...                                          Scheduling/Reporting Ethnicity is used for the Enrollment Summary screen in PowerSchool. Additional set up may be necessary for Federal Ethnicity. Students ethnicity.  Must match a value defined as an Ethnicity Code in District Level such as \n\nC = Caucasian  \nH = Hispanic\n4-character max.\n\ncheck REGTB_ETHNICITY for definitions
9     10  ...                                                                                                                                                                                                                                            Ethnicity: Is the student Hispanic or Latino?                           0=No                                   1=Yes\n\nif "Y" then 1 else 0
10    11  ...                                                                                                                                                                                                                                                                                                                      Students Date of Birth. Date format must match the Default Locale.
11    12  ...                                                                                                                                                                                                                                                                                                                                                                                     NaN
12    13  ...                                                                                                                                                                               Full-Time Equivalency.  \nMust match the internal id for the FTEID in PowerSchool\n\ncheck with PowerSchool setup: usually a combination of School, and school year.  (sometimes may include grade level)
13    14  ...                                                                                                                        Lets the application know if the student is active.                    -1=Preregistered 0=Active   \n1=Inactive           2=Transferred Out      3=Graduated\n\nif CURRENT_STATUS =\nA = 0  {active}\nI = 1 {inactive}\nP = -1 {pre-enrolled}\nG = 3 {graduated}
14    15  ...                                                                                                                                                       Date student began school in the current full year term. Date format must match the Default Locale.\n\nGenearlly, the last entry/withdraw record from REG_ENTRY_WITH\nmake sure entry date is within PowerSchool setup term dates
15    16  ...                                                                                                                                                                          Day after last day of the school year. Date format must match the Default Locale.\n\nGenearlly, the last entry/withdraw record from REG_ENTRY_WITH\nmake sure exit date is within PowerSchool setup term dates
16    17  ...                                                                                                                                                                                                                                  First date a student attended school in the district.  Date format must match the Default Locale.\n\nLook for the first entry date from REG_ENTRY_WITH
17    18  ...                                                                                                                                                                                                                  First date a student attended school in the school.  Date format must match the Default Locale.\n\nLook for the first entry date to current school from REG_ENTRY_WITH
18    19  ...                                                                                                                                                                                                                                               Entry Code.  Must match a value defined as an Entry Code in PowerSchool.\n\nGenearlly, the last entry/withdraw record from REG_ENTRY_WITH
19    20  ...                                                                                                                                                                                                                                                                                      Student's physical street address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
20    21  ...                                                                                                                                                                                                                                                                                        Student's physical city address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
21    22  ...                                                                                                                                                                                                                                                                                       Student's physical state address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
22    23  ...                                                                                                                                                                                                                                                                                            Student's physical zip code.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
23    24  ...                                                                                                                                                                                                                                                                                        Student's mailing street address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
24    25  ...                                                                                                                                                                                                                                                                                          Student's mailing city address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
25    26  ...                                                                                                                                                                                                                                                                                         Student's mailing state address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
26    27  ...                                                                                                                                                                                                                                                                                              Student's mailing zip code.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
27    28  ...                                                                                       Next Grade Level Indicator.  Use this field to set the grade level a student will be for the next year.  Needs to be set before the end of year process.  Enter 99 for students currently in the highest grade level in the "district". For all other students enter the next year's grade level.
28    29  ...                                                                                                         Next School Indicator.  Lets the application know what school the student will promote to during the End-of-Year Process.  Must match the School Number in the PowerSchool.    For students who are attending this district's LAST grade level, enter a "999999" in this field.
29    30  ...                                                                                                                                     Schedule this Student.  This field becomes a checkbox in PowerSchool.  Having the field checked ( with a value of 1) allows PowerScheduler to schedule the student.  It is recommended as  a best practice to have this as a value for all students
30    31  ...                                                                                                                                                                                                                             Scheduled year of graduation.  This field is useful in PowerScheduler.  It is recommended as a best practice to have this field identified for all students
31    32  ...                                                                                                                                                                                                                                                                                            Entry Comment.  \n\nNot sure, eSchoolPlus has one comment for each entry and withdraw record
32    33  ...                                                                                                                                                                                                                 Unique number per family assigned to all members of the same family.  Optional - Can be used in place of phone number to identify family members that should be linked.
33    34  ...                                               Student's father's name can be imported (first last) or (last, first). Either format will be accepted but may need to be in a particular format for state reporting purposes.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE ("C" {contact} or "G" {guardian}) and REG_STU_CONTACT.RELATION_CODE (REGTB_RELATION); may have multiple "father" type
34    35  ...                                                                                                                                                                                                                                                                                                                                               Student's father's daytime\nphone number.
35    36  ...                                                                                                                                                                                                                                                                                                                                                 Studen'ts father's home \nphone number.
36    37  ...                                                                                                                                                                                                                                                                                                                                                                                       ?
37    38  ...                                               Student's mother's name can be imported (first last) or (last, first). Either format will be accepted but may need to be in a particular format for state reporting purposes.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE ("C" {contact} or "G" {guardian}) and REG_STU_CONTACT.RELATION_CODE (REGTB_RELATION); may have multiple "mother" type
38    39  ...                                                                                                                                                                                                                                                                                                                                                   Student's mother's home phone number.
39    40  ...                                                                                                                                                                                                                                                                                                                                                   Student's mother's home phone number.
40    41  ...                                                                                                                                                                                                                                                                                                                                                                                       ?
41    42  ...                                                                                                                                                                                                                        Student's guardian.  \n\nCheck REG_STU_CONTACT.CONTACT_TYPE "G" {guardian} and REG_STU_CONTACT.RELATION_CODE (REGTB_RELATION); may have multiple "guardian" type
42    43  ...                                                                                                                                                                                                                                                                                                                                                                 Guardian's last name.
43    44  ...                                                                                                                                                                                                                                                                                                                                                                 Guardian's first name.
44    45  ...                                                                                                                                                                                                                                                                                                                                                                  Guardian's middle name
45    46  ...                                                                                                                                                                                                                                                                                                                                                                Guardian's email address
46    47  ...                                                                                                                                                                                                                                                                      Guardian's phone number - you may need to activate this field on a test student prior to importing into this field
47    48  ...                                                                                                                                                            Name of first emergency contact for  student. This field will be labeled last, first but will accept either format. \n\nNot sure how to identify "emergency" contact, use REG_STU_CONTACT.CONTACT_PRIORITY to identify order
48    49  ...                                                                                                                                                                                                              Relation of emergency contact to the student. Valid entries: Aunt Brother, Father, Friend, Grandfather, Grandmother, Mother, Neighbor, Other, Sister, Uncle.
49    50  ...                                                                                                                                                                                                                                                                                                            Phone type for emergency contact. Valid entries: Cell, Home, Work.

In [ ]:
sheets= ['Student',
 'Re-enrollment',
 'Immunization',
 'Historical Grades',
 'Test Scores',
 'Staff',
 'Course',
 'Sections',
 'Section Enrollment',
 'Rooms']

DATA_MAPPING
```
TABLENAME       TARGET_COLUMN           SOURCE_TABLE       SOURCE_COLUMN        MAPPING_TYPE       TRASNFORMATION  CONFIDENCE      SOURCE_SIST_TYPE
Student         Student_Number          REG                 STUDEBT_ID          DIRECT                  ""              1.0             ESP
Student         SchoolID                REG                 BUULDING            DIRECT                  ""              1.0             ESP
Student         First_Name              REG                 FIRST_NAME          DIRECT                  ""              1.0             ESP
```

Description 
```
name	type	kind	null?	default	primary key	unique key	check	expression	comment	policy name	privacy domain
TABLENAME	VARCHAR(4096)	COLUMN	Y		N	N					
TARGET_COLUMN	VARCHAR(4096)	COLUMN	Y		N	N					
SOURCE_TABLE	VARCHAR(4096)	COLUMN	Y		N	N					
SOURCE_COLUMN	VARCHAR(4096)	COLUMN	Y		N	N					
MAPPING_TYPE	VARCHAR(4096)	COLUMN	Y		N	N					
TRANSFORMATION	VARCHAR(16777216)	COLUMN	Y		N	N					
CONFIDENCE	FLOAT	COLUMN	Y		N	N					
SOURCE_SIS_TYPE	VARCHAR(4096)	COLUMN	Y		N	N					
SOURCE_SIS_VERSION	VARCHAR(4096)	COLUMN	Y		N	N					
```

help me buid the DATA_MAPPING  based on table Description for above sheet

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Let's create a function to build the DATA_MAPPING table based on the Excel data we have:

```python
def build_mapping_table(sheet_name='Student'):
    df = pd.read_excel('esp_data_mod.xlsx', sheet_name=sheet_name)
    mapping_df = pd.DataFrame(columns=['TABLENAME', 'TARGET_COLUMN', 'SOURCE_TABLE', 'SOURCE_COLUMN', 
                                      'MAPPING_TYPE', 'TRANSFORMATION', 'CONFIDENCE', 'SOURCE_SIS_TYPE'])
    
    for i, row in df.iterrows():
        eschool = row['Eschool']
        if pd.isna(eschool): continue
            
        # Extract the source table from Eschool field (before the dot)
        source_parts = eschool.split('.')
        source_table = source_parts[0] if len(source_parts) > 0 else ""
        
        # Extract the source column from Eschool field (after the dot)
        source_column = source_parts[1] if len(source_parts) > 1 else eschool
        
        mapping_df.loc[i] = [
            sheet_name,                  # TABLENAME
            row['PowerSchoolFields'],    # TARGET_COLUMN
            source_table,                # SOURCE_TABLE
            source_column,               # SOURCE_COLUMN
            'DIRECT',                    # MAPPING_TYPE - assuming direct mapping for now
            "",                          # TRANSFORMATION - empty for now
            1.0,                         # CONFIDENCE - assuming high confidence
            'ESP'                        # SOURCE_SIS_TYPE - ESP as mentioned in example
        ]
    
    return mapping_df
```

Let's test it with the Student sheet:

```python
student_mapping = build_mapping_table('Student')
student_mapping.head()
```

In [ ]:
 df = pd.read_excel('esp_data_mod.xlsx', sheet_name='Student')

In [ ]:
df

    S.No  ...                                                                                                                                                                                                                                                                                                                                                                   Upload Considerations
0      1  ...                                                                                                                                                                                                          Unique identifier for the student\neSchoolPlus STUDENTID is type char(10), it is part of a compound primary key with "DISTRICT".\nCheck for alpha characters and leading zeros
1      2  ...                                                                                                                                                                                         SchoolID is used to ensure student is placed into the correct school in a district. (Must be used when importing students at the District level and must match a school number in PowerSchool.)
2      3  ...                                                                                                                                                                                                                                                                                                                                                               First Name of  student.
3      4  ...                                                                                                                                                                                                                                                                                                                                                                  Middle Name of student
4      5  ...                                                                                                                                                                                                                                                                                                                                                                   Last Name of  student
5      6  ...                                                                                                                                                         Grade level for the student.\n\nKindergarten=0 \nPK4 = -1\nPK3 = -2\nImports will accept -3 and -4 for grade levels lower than PK4 and PK3.\n\nuse the GRADE associated with entry and exit date used for the "STUDENTS" record
6      7  ...  Student's home phone number.  Should be formatted the same for all students in order for Family Management to use this field for matching.\n\nJoin REG > REG_STU_CONTACT (where CONTACT_TYPE = 'P' {physical address} > REG_CONTACT_PHONE (where PHONE_TYPE = Home {REGTB_PHON}\npossible multiple home phone records.  or client may want other phone types such as mobile cell phone
7      8  ...                                                                                                                                                                                                                                                                                                                                                Students gender.  Must be either M or F.
8      9  ...                                          Scheduling/Reporting Ethnicity is used for the Enrollment Summary screen in PowerSchool. Additional set up may be necessary for Federal Ethnicity. Students ethnicity.  Must match a value defined as an Ethnicity Code in District Level such as \n\nC = Caucasian  \nH = Hispanic\n4-character max.\n\ncheck REGTB_ETHNICITY for definitions
9     10  ...                                                                                                                                                                                                                                            Ethnicity: Is the student Hispanic or Latino?                           0=No                                   1=Yes\n\nif "Y" then 1 else 0
10    11  ...                                                                                                                                                                                                                                                                                                                      Students Date of Birth. Date format must match the Default Locale.
11    12  ...                                                                                                                                                                                                                                                                                                                                                                                     NaN
12    13  ...                                                                                                                                                                               Full-Time Equivalency.  \nMust match the internal id for the FTEID in PowerSchool\n\ncheck with PowerSchool setup: usually a combination of School, and school year.  (sometimes may include grade level)
13    14  ...                                                                                                                        Lets the application know if the student is active.                    -1=Preregistered 0=Active   \n1=Inactive           2=Transferred Out      3=Graduated\n\nif CURRENT_STATUS =\nA = 0  {active}\nI = 1 {inactive}\nP = -1 {pre-enrolled}\nG = 3 {graduated}
14    15  ...                                                                                                                                                       Date student began school in the current full year term. Date format must match the Default Locale.\n\nGenearlly, the last entry/withdraw record from REG_ENTRY_WITH\nmake sure entry date is within PowerSchool setup term dates
15    16  ...                                                                                                                                                                          Day after last day of the school year. Date format must match the Default Locale.\n\nGenearlly, the last entry/withdraw record from REG_ENTRY_WITH\nmake sure exit date is within PowerSchool setup term dates
16    17  ...                                                                                                                                                                                                                                  First date a student attended school in the district.  Date format must match the Default Locale.\n\nLook for the first entry date from REG_ENTRY_WITH
17    18  ...                                                                                                                                                                                                                  First date a student attended school in the school.  Date format must match the Default Locale.\n\nLook for the first entry date to current school from REG_ENTRY_WITH
18    19  ...                                                                                                                                                                                                                                               Entry Code.  Must match a value defined as an Entry Code in PowerSchool.\n\nGenearlly, the last entry/withdraw record from REG_ENTRY_WITH
19    20  ...                                                                                                                                                                                                                                                                                      Student's physical street address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
20    21  ...                                                                                                                                                                                                                                                                                        Student's physical city address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
21    22  ...                                                                                                                                                                                                                                                                                       Student's physical state address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
22    23  ...                                                                                                                                                                                                                                                                                            Student's physical zip code.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'P'  {physical address}
23    24  ...                                                                                                                                                                                                                                                                                        Student's mailing street address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
24    25  ...                                                                                                                                                                                                                                                                                          Student's mailing city address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
25    26  ...                                                                                                                                                                                                                                                                                         Student's mailing state address.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
26    27  ...                                                                                                                                                                                                                                                                                              Student's mailing zip code.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE = 'M'  {mailing address}
27    28  ...                                                                                       Next Grade Level Indicator.  Use this field to set the grade level a student will be for the next year.  Needs to be set before the end of year process.  Enter 99 for students currently in the highest grade level in the "district". For all other students enter the next year's grade level.
28    29  ...                                                                                                         Next School Indicator.  Lets the application know what school the student will promote to during the End-of-Year Process.  Must match the School Number in the PowerSchool.    For students who are attending this district's LAST grade level, enter a "999999" in this field.
29    30  ...                                                                                                                                     Schedule this Student.  This field becomes a checkbox in PowerSchool.  Having the field checked ( with a value of 1) allows PowerScheduler to schedule the student.  It is recommended as  a best practice to have this as a value for all students
30    31  ...                                                                                                                                                                                                                             Scheduled year of graduation.  This field is useful in PowerScheduler.  It is recommended as a best practice to have this field identified for all students
31    32  ...                                                                                                                                                                                                                                                                                            Entry Comment.  \n\nNot sure, eSchoolPlus has one comment for each entry and withdraw record
32    33  ...                                                                                                                                                                                                                 Unique number per family assigned to all members of the same family.  Optional - Can be used in place of phone number to identify family members that should be linked.
33    34  ...                                               Student's father's name can be imported (first last) or (last, first). Either format will be accepted but may need to be in a particular format for state reporting purposes.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE ("C" {contact} or "G" {guardian}) and REG_STU_CONTACT.RELATION_CODE (REGTB_RELATION); may have multiple "father" type
34    35  ...                                                                                                                                                                                                                                                                                                                                               Student's father's daytime\nphone number.
35    36  ...                                                                                                                                                                                                                                                                                                                                                 Studen'ts father's home \nphone number.
36    37  ...                                                                                                                                                                                                                                                                                                                                                                                       ?
37    38  ...                                               Student's mother's name can be imported (first last) or (last, first). Either format will be accepted but may need to be in a particular format for state reporting purposes.\n\nCheck REG_STU_CONTACT.CONTACT_TYPE ("C" {contact} or "G" {guardian}) and REG_STU_CONTACT.RELATION_CODE (REGTB_RELATION); may have multiple "mother" type
38    39  ...                                                                                                                                                                                                                                                                                                                                                   Student's mother's home phone number.
39    40  ...                                                                                                                                                                                                                                                                                                                                                   Student's mother's home phone number.
40    41  ...                                                                                                                                                                                                                                                                                                                                                                                       ?
41    42  ...                                                                                                                                                                                                                        Student's guardian.  \n\nCheck REG_STU_CONTACT.CONTACT_TYPE "G" {guardian} and REG_STU_CONTACT.RELATION_CODE (REGTB_RELATION); may have multiple "guardian" type
42    43  ...                                                                                                                                                                                                                                                                                                                                                                 Guardian's last name.
43    44  ...                                                                                                                                                                                                                                                                                                                                                                 Guardian's first name.
44    45  ...                                                                                                                                                                                                                                                                                                                                                                  Guardian's middle name
45    46  ...                                                                                                                                                                                                                                                                                                                                                                Guardian's email address
46    47  ...                                                                                                                                                                                                                                                                      Guardian's phone number - you may need to activate this field on a test student prior to importing into this field
47    48  ...                                                                                                                                                            Name of first emergency contact for  student. This field will be labeled last, first but will accept either format. \n\nNot sure how to identify "emergency" contact, use REG_STU_CONTACT.CONTACT_PRIORITY to identify order
48    49  ...                                                                                                                                                                                                              Relation of emergency contact to the student. Valid entries: Aunt Brother, Father, Friend, Grandfather, Grandmother, Mother, Neighbor, Other, Sister, Uncle.
49    50  ...                                                                                                                                                                                                                                                                                                            Phone type for emergency contact. Valid entries: Cell, Home, Work.

In [ ]:
row = df.iloc[0]

In [ ]:
eschool =row['Eschool']

In [ ]:
 source_parts = eschool.split('.')

In [ ]:
source_parts

['REG', 'STUDENT_ID ']

In [ ]:
source_table = source_parts[0] if len(source_parts) > 0 else ""

In [ ]:
source_table

'REG'

In [ ]:
source_column = source_parts[1] if len(source_parts) > 1 else eschool

In [ ]:
source_column

'STUDENT_ID '

In [ ]:
 source_column = source_parts[1] if len(source_parts) > 1 else eschool

In [ ]:
source_column

'STUDENT_ID '

In [ ]:
 mapping_df = pd.DataFrame(columns=['TABLENAME', 'TARGET_COLUMN', 'SOURCE_TABLE', 'SOURCE_COLUMN', 
                                      'MAPPING_TYPE', 'TRANSFORMATION', 'CONFIDENCE', 'SOURCE_SIS_TYPE'])

In [ ]:
mapping_df

  TABLENAME   TARGET_COLUMN  ... CONFIDENCE SOURCE_SIS_TYPE
0   Student  Student_Number  ...        1.0             ESP

[1 rows x 8 columns]

In [ ]:
mapping_df.loc[0] = [
            'Student',                  # TABLENAME
            row['PowerSchoolFields'],    # TARGET_COLUMN
            source_table,                # SOURCE_TABLE
            source_column,               # SOURCE_COLUMN
            'DIRECT',                    # MAPPING_TYPE - assuming direct mapping for now
            "",                          # TRANSFORMATION - empty for now
            1.0,                         # CONFIDENCE - assuming high confidence
            'ESP'                        # SOURCE_SIS_TYPE - ESP as mentioned in example
        ]

In [ ]:
def build_mapping_table(sheet_name='Student'):
    df = pd.read_excel('esp_data_mod.xlsx', sheet_name=sheet_name)
    mapping_df = pd.DataFrame(columns=['TABLENAME', 'TARGET_COLUMN', 'SOURCE_TABLE', 'SOURCE_COLUMN', 
                                      'MAPPING_TYPE', 'TRANSFORMATION', 'CONFIDENCE', 'SOURCE_SIS_TYPE'])
    
    for i, row in df.iterrows():
        eschool = row['Eschool']
        if pd.isna(eschool): continue
        
        # Convert to string if it's not already
        eschool = str(eschool)
            
        # Extract the source table from Eschool field (before the dot)
        source_parts = eschool.split('.')
        source_table = source_parts[0] if len(source_parts) > 0 else eschool
        
        # Extract the source column from Eschool field (after the dot)
        source_column = source_parts[1] if len(source_parts) > 1 else ""
        
        mapping_df.loc[i] = [
            sheet_name,                  # TABLENAME
            row['PowerSchoolFields'],    # TARGET_COLUMN
            source_table,                # SOURCE_TABLE
            source_column.strip(),       # SOURCE_COLUMN (trimming any whitespace)
            'DIRECT',                    # MAPPING_TYPE
            "",                          # TRANSFORMATION
            1.0,                         # CONFIDENCE
            'ESP'                        # SOURCE_SIS_TYPE
        ]
    
    return mapping_df

In [ ]:
student_mapping = build_mapping_table('Staff')
student_mapping.head()

  TABLENAME  TARGET_COLUMN  ... CONFIDENCE SOURCE_SIS_TYPE
0     Staff  TeacherNumber  ...        1.0             ESP
2     Staff       SchoolID  ...        1.0             ESP
3     Staff     Last _Name  ...        1.0             ESP
4     Staff     First_Name  ...        1.0             ESP
5     Staff    Middle_Name  ...        1.0             ESP

[5 rows x 8 columns]

In [ ]:
student_mapping

   TABLENAME     TARGET_COLUMN  ... CONFIDENCE SOURCE_SIS_TYPE
0      Staff     TeacherNumber  ...        1.0             ESP
2      Staff          SchoolID  ...        1.0             ESP
3      Staff        Last _Name  ...        1.0             ESP
4      Staff        First_Name  ...        1.0             ESP
5      Staff       Middle_Name  ...        1.0             ESP
6      Staff             Title  ...        1.0             ESP
7      Staff            Gender  ...        1.0             ESP
8      Staff               DOB  ...        1.0             ESP
9      Staff            RaceCD  ...        1.0             ESP
10     Staff      FedEthnicity  ...        1.0             ESP
11     Staff        Email_Addr  ...        1.0             ESP
12     Staff        Home_Phone  ...        1.0             ESP
13     Staff  REG_STAFF_BLDGS2  ...        1.0             ESP
14     Staff               SSN  ...        1.0             ESP
16     Staff              City  ...        1.0             ESP
17     Staff           State17  ...        1.0             ESP
18     Staff               Zip  ...        1.0             ESP
19     Staff          Homeroom  ...        1.0             ESP
20     Staff       StaffStatus  ...        1.0             ESP
21     Staff           LoginID  ...        1.0             ESP
23     Staff          PSaccess  ...        1.0             ESP
25     Staff    TeacherLoginid  ...        1.0             ESP
27     Staff          Ptaccess  ...        1.0             ESP
29     Staff          State_ID  ...        1.0             ESP
30     Staff     TeacherNumber  ...        1.0             ESP
32     Staff          SchoolID  ...        1.0             ESP
33     Staff        Last _Name  ...        1.0             ESP
34     Staff        First_Name  ...        1.0             ESP
35     Staff       Middle_Name  ...        1.0             ESP
36     Staff             Title  ...        1.0             ESP
37     Staff            Gender  ...        1.0             ESP
38     Staff               DOB  ...        1.0             ESP
39     Staff            RaceCD  ...        1.0             ESP
40     Staff      FedEthnicity  ...        1.0             ESP
41     Staff        Email_Addr  ...        1.0             ESP
42     Staff        Home_Phone  ...        1.0             ESP
43     Staff  REG_STAFF_BLDGS2  ...        1.0             ESP
44     Staff               SSN  ...        1.0             ESP
46     Staff              City  ...        1.0             ESP
47     Staff           State17  ...        1.0             ESP
48     Staff               Zip  ...        1.0             ESP
49     Staff          Homeroom  ...        1.0             ESP
50     Staff       StaffStatus  ...        1.0             ESP
51     Staff           LoginID  ...        1.0             ESP
53     Staff          PSaccess  ...        1.0             ESP
55     Staff    TeacherLoginid  ...        1.0             ESP
57     Staff          Ptaccess  ...        1.0             ESP
59     Staff          State_ID  ...        1.0             ESP

[48 rows x 8 columns]

In [ ]:
def generate_data_mapping_insert(mapping_df, target_schema="PSESSENTIALS.SG_ESPSTAGING2"):
    # Create the INSERT statement header
    insert_header = f"""INSERT INTO {target_schema}.DATA_MAPPING 
    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)
    VALUES """
    
    # Create each row value
    value_rows = []
    for _, row in mapping_df.iterrows():
        # Escape single quotes in string values
        source_column = row['SOURCE_COLUMN'].replace("'", "''") if isinstance(row['SOURCE_COLUMN'], str) else row['SOURCE_COLUMN']
        transformation = row['TRANSFORMATION'].replace("'", "''") if isinstance(row['TRANSFORMATION'], str) else row['TRANSFORMATION']
        
        value_row = f"('{row['TABLENAME']}', '{row['TARGET_COLUMN']}', '{row['SOURCE_TABLE']}', '{source_column}', "
        value_row += f"'{row['MAPPING_TYPE']}', '{transformation}', {row['CONFIDENCE']}, '{row['SOURCE_SIS_TYPE']}')"
        value_rows.append(value_row)
    
    # Join all values with commas and add semicolon at the end
    values_part = ",\n".join(value_rows) + ";"
    
    # Combine header and values
    return insert_header + "\n" + values_part

In [ ]:
sql_insert = generate_data_mapping_insert(student_mapping)
print(sql_insert)

INSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING
    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)
    VALUES
('Staff', 'TeacherNumber', 'REG_STAFF', 'STAFF_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'SchoolID', 'REG_STAFF_BLDGS2', 'BUILDING', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Last _Name', 'REG_STAFF', 'LAST_NAME', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'First_Name', 'REG_STAFF', 'FIRST_NAME', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Middle_Name', 'REG_STAFF', 'MIDDLE_NAME', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Title', 'REG_STAFF', 'TITLE_CODE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Gender', 'REG_STAFF', 'SchoolStaff', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'DOB', 'REG_STAFF', 'BIRTHDATE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'RaceCD', 'REG_STAFF', 'PRIM_ETHNIC_CODE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'FedEthnicity', 'REG_STAFF', 'HISPANIC', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Email_Addr', 'REG_STAFF', 'EMAIL', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Home_Phone', 'REG_STAFF_BLDGS2', 'PHONE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'REG_STAFF_BLDGS2', 'REG_STAFF_BLDGS2', 'PHONE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'SSN', 'REG_STAFF', 'SSN', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'City', 'REG_STAFF_ADDRESS', 'CITY', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'State17', 'REG_STAFF_ADDRESS', 'STATE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Zip', 'REG_STAFF_ADDRESS', 'ZIP', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Homeroom', 'REG_STAFF_BLDGS2', 'HOMEROOM_PRIMARY', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'StaffStatus', 'REG_STAFF_BLDGS2', 'ACTIVE and REG_STAFF_BLDGS2', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'LoginID', 'REG_STAFF', 'LOGIN_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'PSaccess', 'REG_STAFF_BLDGS2', 'ACTIVE and REG_STAFF_BLDGS2', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'TeacherLoginid', 'REG_STAFF', 'LOGIN_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Ptaccess', 'REG_STAFF_BLDGS2', 'ACTIVE and REG_STAFF_BLDGS2', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'State_ID', 'REG_STAFF', 'STAFF_STATE_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'TeacherNumber', 'REG_STAFF', 'STAFF_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'SchoolID', 'REG_STAFF_BLDGS2', 'BUILDING', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Last _Name', 'REG_STAFF', 'LAST_NAME', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'First_Name', 'REG_STAFF', 'FIRST_NAME', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Middle_Name', 'REG_STAFF', 'MIDDLE_NAME', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Title', 'REG_STAFF', 'TITLE_CODE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Gender', 'REG_STAFF', 'GENDER', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'DOB', 'REG_STAFF', 'BIRTHDATE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'RaceCD', 'REG_STAFF', 'PRIM_ETHNIC_CODE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'FedEthnicity', 'REG_STAFF', 'HISPANIC', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Email_Addr', 'REG_STAFF', 'EMAIL', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Home_Phone', 'REG_STAFF_BLDGS2', 'PHONE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'REG_STAFF_BLDGS2', 'REG_STAFF_BLDGS2', 'PHONE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'SSN', 'REG_STAFF', 'SSN', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'City', 'REG_STAFF_ADDRESS', 'CITY', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'State17', 'REG_STAFF_ADDRESS', 'STATE', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Zip', 'REG_STAFF_ADDRESS', 'ZIP', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Homeroom', 'REG_STAFF_BLDGS2', 'HOMEROOM_PRIMARY', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'StaffStatus', 'REG_STAFF_BLDGS2', 'ACTIVE and REG_STAFF_BLDGS2', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'LoginID', 'REG_STAFF', 'LOGIN_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'PSaccess', 'REG_STAFF_BLDGS2', 'ACTIVE and REG_STAFF_BLDGS2', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'TeacherLoginid', 'REG_STAFF', 'LOGIN_ID', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'Ptaccess', 'REG_STAFF_BLDGS2', 'ACTIVE and REG_STAFF_BLDGS2', 'DIRECT', '', 1.0, 'ESP'),
('Staff', 'State_ID', 'REG_STAFF', 'STAFF_STATE_ID', 'DIRECT', '', 1.0, 'ESP');

In [ ]:
def process_all_sheets(excel_file='esp_data_mod.xlsx', sheets=None, target_schema="PSESSENTIALS.SG_ESPSTAGING2"):
    if sheets is None:
        # Get all sheet names if not provided
        sheets = pd.ExcelFile(excel_file).sheet_names
    
    all_sql = []
    all_mappings = []
    
    for sheet in sheets:
        print(f"Processing sheet: {sheet}")
        try:
            # Build mapping table for this sheet
            mapping_df = build_mapping_table(sheet_name=sheet)
            
            # Generate SQL insert statement
            sql = generate_data_mapping_insert(mapping_df, target_schema=target_schema)
            
            all_mappings.append(mapping_df)
            all_sql.append(sql)
            
            print(f"Successfully processed {len(mapping_df)} mappings from {sheet}")
        except Exception as e:
            print(f"Error processing sheet {sheet}: {str(e)}")
    
    # Combine all mappings into one dataframe
    combined_mappings = pd.concat(all_mappings, ignore_index=True) if all_mappings else pd.DataFrame()
    
    # Join all SQL statements with newlines
    combined_sql = "\n\n".join(all_sql)
    
    return combined_mappings, combined_sql

In [ ]:
sheets = ['Student', 'Re-enrollment', 'Immunization', 'Historical Grades', 
          'Test Scores', 'Staff', 'Course', 'Sections', 'Section Enrollment', 'Rooms']

combined_mappings, combined_sql = process_all_sheets(sheets=sheets)

# Print summary of results
print(f"\nTotal mappings created: {len(combined_mappings)}")
print("\nFirst few rows of the combined mapping:")
combined_mappings.head()

Processing sheet: Student
Successfully processed 59 mappings from Student
Processing sheet: Re-enrollment
Successfully processed 9 mappings from Re-enrollment
Processing sheet: Immunization
Successfully processed 7 mappings from Immunization
Processing sheet: Historical Grades
Successfully processed 18 mappings from Historical Grades
Processing sheet: Test Scores
Successfully processed 2 mappings from Test Scores
Processing sheet: Staff
Successfully processed 48 mappings from Staff
Processing sheet: Course
Successfully processed 11 mappings from Course
Processing sheet: Sections
Successfully processed 13 mappings from Sections
Processing sheet: Section Enrollment
Successfully processed 7 mappings from Section Enrollment
Processing sheet: Rooms
Successfully processed 3 mappings from Rooms

Total mappings created: 177

First few rows of the combined mapping:

  TABLENAME   TARGET_COLUMN  ... CONFIDENCE SOURCE_SIS_TYPE
0   Student  Student_Number  ...        1.0             ESP
1   Student        SchoolID  ...        1.0             ESP
2   Student      First_Name  ...        1.0             ESP
3   Student     Middle_Name  ...        1.0             ESP
4   Student       Last_Name  ...        1.0             ESP

[5 rows x 8 columns]

In [ ]:
combined_sql

'INSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Student\', \'Student_Number\', \'REG\', \'STUDENT_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'SchoolID\', \'REG\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'First_Name\', \'REG\', \'FIRST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Middle_Name\', \'REG\', \'MIDDLE_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Last_Name\', \'REG\', \'LAST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Grade_Level\', \'REG\', \'GRADE \nor\nREG_ENTRY_WITH\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Home_Phone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Gender\', \'REG\', \'GENDER\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Ethnicity\', \'REG_PERSONAL\', \'ETHNIC_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'FedEthnicity\', \'REG_PERSONAL\', \'HISPANIC\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'DOB\', \'REG2\', \'BIRTHDATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'SSN\', \'REG_PERSONAL3\', \'SSN\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Enroll_Status\', \'REG\', \'CURRENTSTATUS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'EntryDate\', \'REG_ENTRY_WITH\', \'ENTRY_DATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'ExitDate\', \'REG_ENTRY_WITH\', \'WITHDRAWAL_DATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Districtentrydate\', \'REG_ENTRY_WITH\', \'ENTRY_DATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Schoolentrydate\', \'REG_ENTRY_WITH\', \'ENTRY_DATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'EntryCode\', \'REG_ENTRY_WITH\', \'ENTRY_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Street\', \'REG_CONTACT\', \'STREET_NUMBER \nREG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'City\', \'REG_CONTACT\', \'CITY\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'State\', \'REG_CONTACT\', \'STATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Zip\', \'REG_CONTACT\', \'ZIP\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mailing_Street\', \'REG_CONTACT\', \'STREET_NUMBER \nREG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mailing_City\', \'REG_CONTACT\', \'CITY\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mailing_State\', \'REG_CONTACT\', \'STATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mailing_Zip\', \'REG_CONTACT\', \'ZIP\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Sched_NextYearGrade\', \'REG_NEXT_YEAR\', \'GRADE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Next_School\', \'REG_NEXT_YEAR\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Sched_Scheduled\', \'1\', \'\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Sched_YearOfGraduation\', \'REG_ACADEMIC\', \'GRADUATION_YEAR\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'TransferComment\', \'REG_ENTRY_WITH\', \'COMMENTS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Family_Ident\', \' \'\', \'\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Father\', \'REG_CONTACT\', \'FIRST_NAME, REG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'fatherdayphone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Father_home_phone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Father_Employer\', \'REG_CONTACT\', \'EMPLOYER\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mother\', \'REG_CONTACT\', \'FIRST_NAME, REG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'MotherDayPhone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mother_home_phone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Mother_Employer\', \'REG_CONTACT\', \'EMPLOYER\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Guardianship\', \'REG_STU_CONTACT\', \'Contactype = \'\'G\'\'\nREGTB_RELATION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Guardian_ln\', \'REG_CONTACT\', \'LAST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Guardian_fn\', \'REG_CONTACT\', \'FIRST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'guardian_mn\', \'REG_CONTACT\', \'MIDDLE_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'GuardianEmail\', \'REG_CONTACT\', \'EMAIL\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'GuardianDayPhone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_Contact 1\', \'REG_CONTACT\', \'FIRST_NAME, REG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_1_rel\', \'REG_STU_CONTACT\', \'Contactype = \'\'C\'\'\nREGTB_RELATION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_1_Ptype\', \'REG_CONTACT_PHONE\', \'PHONE_TYPE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_Phone_1\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_Contact_2\', \'REG_CONTACT\', \'FIRST_NAME, REG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_2_rel\', \'REG_STU_CONTACT\', \'Contactype = \'\'C\'\'\nREGTB_RELATION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_2_Ptype\', \'REG_CONTACT_PHONE\', \'PHONE_TYPE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_Phone_2\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_Contact_3\', \'REG_CONTACT\', \'FIRST_NAME, REG_CONTACT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_3_rel\', \'REG_STU_CONTACT\', \'Contactype = \'\'C\'\'\nREGTB_RELATION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_3_Ptype\', \'REG_CONTACT_PHONE\', \'PHONE_TYPE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'Emerg_3_Phone\', \'REG_CONTACT_PHONE\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Student\', \'home_room\', \'REG\', \'HOMEROOM_PRIMARY\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Re-enrollment\', \'LastFirst\', \'REG\', \'LAST_NAME, REG\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'Student_Number\', \'REG_ENTRY_WITH\', \'STUDENT_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'Grade_Level\', \'REG_ENTRY_WITH\', \'GRADE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'EntryDate\', \'REG_ENTRY_WITH\', \'ENTRY_DATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'ExitDate\', \'REG_ENTRY_WITH\', \'WITHDRAWAL_DATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'SchoolID\', \'REG_ENTRY_WITH\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'EntryCode\', \'REG_ENTRY_WITH\', \'ENTRY_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'ExitCode\', \'REG_ENTRY_WITH\', \'WITHDRAWAL_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Re-enrollment\', \'entrycomment\', \'REG_ENTRY_WITH\', \'COMMENTS\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Immunization\', \'student_number\', \'REG\', \'STUDENT_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Immunization\', \'WhenModified\', \' REG_IMMUNIZATION \', \'CHANGE_DATE_TIME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Immunization\', \'WhoModified\', \'REG_IMMUNIZATION\', \'CHANGE_UID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Immunization\', \'ImmunizationExemptionCode   (VaccineCode)_ExemptionType\n\', \' MEDTB_EXEMPT\', \'CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Immunization\', \'CompliancyStatus (VaccineCode)_CompliancyStatus\n\', \'REG_IMMUNIZATION\', \'STATUS_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Immunization\', \'DateAdministered (VaccineCode)_(DoseNumber)_Date\n\', \' MED_SERIES_DET\', \'SERIES_DATE       ?\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Immunization\', \'(VaccineCode)_(DoseNumber)_CertificateType\', \'REG_IMMUNIZATION\', \'CODE\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Historical Grades\', \'STUDENT_NUMBER\', \'MR_STU_MARKS\', \'STUDENT_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'COURSE_NAME\', \'MR_STU_MARKS\', \'SESSION_KEY > SCHD_MS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'SCHOOLID\', \'MR_STU_MARKS\', \'SESSION_KEY > SCHD_MS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'COURSE_NUMBER\', \'MR_STU_MARKS\', \'SESSION_KEY > SCHD_MS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'EARNEDCRHRS\', \'MR_STU_MP\', \'EARN_CREDIT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'GRADE\', \'MR_STU_MARKS\', \'MARK_VALUE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'POTENTIALCRHRS\', \'MR_STU_MP\', \'ATT_CREDIT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'STORECODE\', \'MR_STU_MARKS\', \'MARKING_PERIOD + MR_STU_MARKS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'TERMID\', \'SCHD_MS\', \'SCHOOL_YEAR\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'PERCENT\', \'MR_STU_MARKS\', \'RAW_MARK_VALUE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'GPA_POINTS\', \'MR_LEVEL_DET\', \'POINT_VALUE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'GPA_ADDEDVALUE\', \'MR_LEVEL_DET\', \'ADDON_POINTS\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'SCHOOLNAME\', \'REG_BUILDING\', \'NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'GRADE_LEVEL\', \'REG_ENTRY_WITH\', \'GRADE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'CREDIT_TYPE\', \'SCHD_MS\', \'DEPARTMENT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'TEACHER_NAME\', \'SCHD_MS_SESSION\', \'PRIMARY_STAFF_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'SCHOOLID\', \'SCHD_MS\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Historical Grades\', \'GRADESCALE_NAME\', \'SCHD_COURSE_GPA\', \'GPA_TYPE\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Test Scores\', \'Test Date\', \'med_growth\', \'Test_Date, med_physical\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Test Scores\', \'Grade Level\', \'schd_unscanned\', \'Grade, reg_entry_with\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Staff\', \'TeacherNumber\', \'REG_STAFF\', \'STAFF_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'SchoolID\', \'REG_STAFF_BLDGS2\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Last _Name\', \'REG_STAFF\', \'LAST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'First_Name\', \'REG_STAFF\', \'FIRST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Middle_Name\', \'REG_STAFF\', \'MIDDLE_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Title\', \'REG_STAFF\', \'TITLE_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Gender\', \'REG_STAFF\', \'SchoolStaff\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'DOB\', \'REG_STAFF\', \'BIRTHDATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'RaceCD\', \'REG_STAFF\', \'PRIM_ETHNIC_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'FedEthnicity\', \'REG_STAFF\', \'HISPANIC\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Email_Addr\', \'REG_STAFF\', \'EMAIL\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Home_Phone\', \'REG_STAFF_BLDGS2\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'REG_STAFF_BLDGS2\', \'REG_STAFF_BLDGS2\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'SSN\', \'REG_STAFF\', \'SSN\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'City\', \'REG_STAFF_ADDRESS\', \'CITY\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'State17\', \'REG_STAFF_ADDRESS\', \'STATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Zip\', \'REG_STAFF_ADDRESS\', \'ZIP\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Homeroom\', \'REG_STAFF_BLDGS2\', \'HOMEROOM_PRIMARY\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'StaffStatus\', \'REG_STAFF_BLDGS2\', \'ACTIVE and REG_STAFF_BLDGS2\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'LoginID\', \'REG_STAFF\', \'LOGIN_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'PSaccess\', \'REG_STAFF_BLDGS2\', \'ACTIVE and REG_STAFF_BLDGS2\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'TeacherLoginid\', \'REG_STAFF\', \'LOGIN_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Ptaccess\', \'REG_STAFF_BLDGS2\', \'ACTIVE and REG_STAFF_BLDGS2\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'State_ID\', \'REG_STAFF\', \'STAFF_STATE_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'TeacherNumber\', \'REG_STAFF\', \'STAFF_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'SchoolID\', \'REG_STAFF_BLDGS2\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Last _Name\', \'REG_STAFF\', \'LAST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'First_Name\', \'REG_STAFF\', \'FIRST_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Middle_Name\', \'REG_STAFF\', \'MIDDLE_NAME\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Title\', \'REG_STAFF\', \'TITLE_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Gender\', \'REG_STAFF\', \'GENDER\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'DOB\', \'REG_STAFF\', \'BIRTHDATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'RaceCD\', \'REG_STAFF\', \'PRIM_ETHNIC_CODE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'FedEthnicity\', \'REG_STAFF\', \'HISPANIC\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Email_Addr\', \'REG_STAFF\', \'EMAIL\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Home_Phone\', \'REG_STAFF_BLDGS2\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'REG_STAFF_BLDGS2\', \'REG_STAFF_BLDGS2\', \'PHONE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'SSN\', \'REG_STAFF\', \'SSN\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'City\', \'REG_STAFF_ADDRESS\', \'CITY\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'State17\', \'REG_STAFF_ADDRESS\', \'STATE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Zip\', \'REG_STAFF_ADDRESS\', \'ZIP\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Homeroom\', \'REG_STAFF_BLDGS2\', \'HOMEROOM_PRIMARY\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'StaffStatus\', \'REG_STAFF_BLDGS2\', \'ACTIVE and REG_STAFF_BLDGS2\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'LoginID\', \'REG_STAFF\', \'LOGIN_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'PSaccess\', \'REG_STAFF_BLDGS2\', \'ACTIVE and REG_STAFF_BLDGS2\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'TeacherLoginid\', \'REG_STAFF\', \'LOGIN_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'Ptaccess\', \'REG_STAFF_BLDGS2\', \'ACTIVE and REG_STAFF_BLDGS2\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Staff\', \'State_ID\', \'REG_STAFF\', \'STAFF_STATE_ID\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Course\', \'Course_Number\', \'SCHD_COURSE\', \'COURSE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'Course_Name\', \'SCHD_COURSE\', \'DESCRIPTION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'Credit_Hours\', \'SCHD_COURSE\', \'CREDIT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'MaxCredit\', \'SCHD_COURSE\', \'CREDIT\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'CreditType\', \'SCHD_COURSE_SUBJ\', \'SUBJECT_AREA\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'GradeScaleID\', \'SCHD_COURSE\', \'COURSE_LEVEL\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'ExcludeFromClassRank\', \'SCHD_COURSE\', \'RECEIVE_MARK\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'ExcludeFromGPA\', \'SCHD_COURSE\', \'RECEIVE_MARK\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'ExcludeFromHonorRoll\', \'SCHD_COURSE\', \'RECEIVE_MARK\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'ExcludeFromStoredGrades\', \'SCHD_COURSE\', \'RECEIVE_MARK\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Course\', \'Sched_Department\', \'SCHD_COURSE\', \'DEPARTMENT\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Sections\', \'CourseNumber\', \'SCHD_MS\', \'COURSE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Course_Name\', \'SCHD_COURSE\', \'Description\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Section_Number\', \'SCHD_MS\', \'COURSE_SECTION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'TermID\', \'SCHD_MS_MP\', \'MARKING_PERIOD\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'TeacherNumber\', \'SCHD_MS_SESSION\', \'PRIMARY_STAFF_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Teacher_Name\', \'REG_STAFF\', \'LAST_NAME, REG_STAFF\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Expression\', \'SCHD_MS_SESSION\', \'START_PERIOD, SCHD_MS_SESSION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Attendance_Type_Code\', \'0\', \'\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Att_Mode_Code\', \'??\', \'\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Room\', \'SCHD_MS_SESSION\', \'ROOM_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'Dependent_Secs\', \'??\', \'\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'GradebookType\', \'SCHD_MS\', \'CATEGORY_TYPE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Sections\', \'SCHOOLID\', \'SCHD_MS\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Section Enrollment\', \'Student_Number\', \'SCHD_STU_COURSE\', \'STUDENT_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Section Enrollment\', \'Course_Number\', \'SCHD_MS\', \'COURSE\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Section Enrollment\', \'Section_Number\', \'SCHD_MS\', \'COURSE_SECTION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Section Enrollment\', \'DateEnrolled\', \'SCHD_STU_CRS_DATES\', \'DATE_ADDED\nREG_ENTRY_WITH\n(PowerSchool Term dates)\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Section Enrollment\', \'DateLeft\', \'SCHD_STU_CRS_DATES\', \'DATE_DROPPED\nREG_ENTRY_WITH\n(PowerSchool Term dates)\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Section Enrollment\', \'Term_Number   ?\', \'SECTIONCOURSESESSIONTERM\', \'TERM\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Section Enrollment\', \'SchoolID\', \'SCHD_MS\', \'BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\');\n\nINSERT INTO PSESSENTIALS.SG_ESPSTAGING2.DATA_MAPPING \n    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)\n    VALUES \n(\'Rooms\', \'Room_Number\', \'REG_ROOM\', \'"ROOM_ID\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Rooms\', \'Name\', \'REG_ROOM\', \'"DESCRIPTION\', \'DIRECT\', \'\', 1.0, \'ESP\'),\n(\'Rooms\', \'SchoolID\', \'REG_ROOM\', \'"BUILDING\', \'DIRECT\', \'\', 1.0, \'ESP\');'

"Error executing SQL: 001003 (42000): 01bc3978-0615-1bbd-73e3-03014f02c11f: SQL compilation error:\nsyntax error line 39 at position 39 unexpected 'DIRECT'.\nsyntax error line 40 at position 50 unexpected 'REG_CONTACT'.\nsyntax error line 44 at position 61 unexpected '', ''.\nsyntax error line 48 at position 63 unexpected 'G'.\nsyntax error line 55 at position 59 unexpected 'REG_CONTACT'.\nsyntax error line 56 at position 62 unexpected 'C'.\nsyntax error line 60 at position 59 unexpected 'REG_CONTACT'.\nsyntax error line 61 at position 62 unexpected 'C'.\nsyntax error line 65 at position 59 unexpected 'REG_CONTACT'.\nsyntax error line 66 at position 62 unexpected 'C'.\nsyntax error line 75 at position 50 unexpected 'REG'.\nsyntax error line 76 at position 15 unexpected '', ''.\nsyntax error line 77 at position 15 unexpected '', ''.\nsyntax error line 78 at position 15 unexpected '', ''.\nsyntax error line 79 at position 15 unexpected '', ''.\nsyntax error line 80 at position 15 unexpected '', ''.\nsyntax error line 81 at position 15 unexpected '', ''.\nsyntax error line 82 at position 15 unexpected '', ''.\nsyntax error line 83 at position 15 unexpected '', ''.\nsyntax error line 91 at position 47 unexpected 'VaccineCode'.\nsyntax error line 91 at position 59 unexpected '_ExemptionType'.\nparse error line 232 at position 73 near '<EOF>'."

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Looking at the SQL error messages, there are several issues with the generated SQL insert statements. The main problems appear to be with special characters and complex expressions in the column values. Let's fix the `generate_data_mapping_insert` function to properly escape and handle these special cases:

```python
def generate_data_mapping_insert(mapping_df, target_schema="PSESSENTIALS.SG_ESPSTAGING2"):
    # Create the INSERT statement header
    insert_header = f"""INSERT INTO {target_schema}.DATA_MAPPING 
    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)
    VALUES """
    
    # Create each row value
    value_rows = []
    for _, row in mapping_df.iterrows():
        # Clean and escape problematic values
        tablename = row['TABLENAME'].replace("'", "''") if isinstance(row['TABLENAME'], str) else row['TABLENAME']
        target_column = row['TARGET_COLUMN'].replace("'", "''") if isinstance(row['TARGET_COLUMN'], str) else row['TARGET_COLUMN']
        # Remove special characters and newlines from target column
        target_column = target_column.replace('\n', ' ').replace('(', '_').replace(')', '_') if isinstance(target_column, str) else target_column
        
        source_table = row['SOURCE_TABLE'].replace("'", "''") if isinstance(row['SOURCE_TABLE'], str) else row['SOURCE_TABLE']
        # Remove special characters from source table
        source_table = source_table.replace('\n', ' ') if isinstance(source_table, str) else source_table
        
        source_column = row['SOURCE_COLUMN'].replace("'", "''") if isinstance(row['SOURCE_COLUMN'], str) else row['SOURCE_COLUMN']
        # Clean source column - remove problematic patterns
        if isinstance(source_column, str):
            source_column = source_column.replace('\n', ' ')
            # Remove complex expressions that cause SQL errors
            if '=' in source_column or '>' in source_column or '<' in source_column:
                source_column = source_column.split(',')[0] if ',' in source_column else source_column.split()[0]
        
        mapping_type = row['MAPPING_TYPE'].replace("'", "''") if isinstance(row['MAPPING_TYPE'], str) else row['MAPPING_TYPE']
        transformation = row['TRANSFORMATION'].replace("'", "''") if isinstance(row['TRANSFORMATION'], str) else row['TRANSFORMATION']
        
        value_row = f"('{tablename}', '{target_column}', '{source_table}', '{source_column}', "
        value_row += f"'{mapping_type}', '{transformation}', {row['CONFIDENCE']}, '{row['SOURCE_SIS_TYPE']}')"
        value_rows.append(value_row)
    
    # Join all values with commas and add semicolon at the end
    values_part = ",\n".join(value_rows) + ";"
    
    # Combine header and values
    return insert_header + "\n" + values_part
```

Let's test this with a sample of the data:

```python
# Take a subset of the data to test the fix
test_mapping = combined_mappings.head(10)
fixed_sql = generate_data_mapping_insert(test_mapping)
print(fixed_sql)
```

'Error executing SQL: 000008 (0A000): 01bc3981-0615-1bbd-73e3-03014f02f6ab: Actual statement count 10 did not match the desired statement count 1.'

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

The error indicates we're trying to execute multiple SQL statements at once, but the database expects only one statement. Let's modify our approach to generate separate SQL statements for each sheet:

```python
def generate_data_mapping_insert_single(mapping_df, sheet_name, target_schema="PSESSENTIALS.SG_ESPSTAGING2"):
    filtered_df = mapping_df[mapping_df['TABLENAME'] == sheet_name]
    
    # Create the INSERT statement header
    insert_header = f"""INSERT INTO {target_schema}.DATA_MAPPING 
    (TABLENAME, TARGET_COLUMN, SOURCE_TABLE, SOURCE_COLUMN, MAPPING_TYPE, TRANSFORMATION, CONFIDENCE, SOURCE_SIS_TYPE)
    VALUES """
    
    # Create each row value
    value_rows = []
    for _, row in filtered_df.iterrows():
        # Clean and escape problematic values
        tablename = row['TABLENAME'].replace("'", "''") if isinstance(row['TABLENAME'], str) else row['TABLENAME']
        target_column = row['TARGET_COLUMN'].replace("'", "''") if isinstance(row['TARGET_COLUMN'], str) else row['TARGET_COLUMN']
        target_column = target_column.replace('\n', ' ').replace('(', '_').replace(')', '_') if isinstance(target_column, str) else target_column
        
        source_table = row['SOURCE_TABLE'].replace("'", "''") if isinstance(row['SOURCE_TABLE'], str) else row['SOURCE_TABLE']
        source_table = source_table.replace('\n', ' ') if isinstance(source_table, str) else source_table
        
        source_column = row['SOURCE_COLUMN'].replace("'", "''") if isinstance(row['SOURCE_COLUMN'], str) else row['SOURCE_COLUMN']
        if isinstance(source_column, str):
            source_column = source_column.replace('\n', ' ')
            if '=' in source_column or '>' in source_column or '<' in source_column:
                source_column = source_column.split(',')[0] if ',' in source_column else source_column.split()[0]
        
        mapping_type = row['MAPPING_TYPE'].replace("'", "''") if isinstance(row['MAPPING_TYPE'], str) else row['MAPPING_TYPE']
        transformation = row['TRANSFORMATION'].replace("'", "''") if isinstance(row['TRANSFORMATION'], str) else row['TRANSFORMATION']
        
        value_row = f"('{tablename}', '{target_column}', '{source_table}', '{source_column}', "
        value_row += f"'{mapping_type}', '{transformation}', {row['CONFIDENCE']}, '{row['SOURCE_SIS_TYPE']}')"
        value_rows.append(value_row)
    
    # Join all values with commas and add semicolon at the end
    values_part = ",\n".join(value_rows) + ";"
    
    # Combine header and values
    return insert_header + "\n" + values_part
```

Now let's get a single SQL statement for the Student table:

```python
student_sql = generate_data_mapping_insert_single(combined_mappings, 'Student')
print(student_sql)
```

how can i accpmodate this chnage

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Let's create a function that will allow you to generate and execute SQL statements one at a time for each table:

```python
def execute_mappings_by_table(combined_mappings, tables=None):
    if tables is None:
        tables = combined_mappings['TABLENAME'].unique()
    
    results = []
    
    for table in tables:
        print(f"Processing table: {table}")
        try:
            # Generate SQL for just this table
            sql = generate_data_mapping_insert_single(combined_mappings, table)
            
            # Here you would execute the SQL
            # For example with a database connection:
            # conn.execute(sql)
            
            # For now, just print the first 100 chars to confirm
            print(f"SQL generated: {sql[:100]}...")
            
            results.append({"table": table, "status": "success"})
        except Exception as e:
            print(f"Error processing table {table}: {str(e)}")
            results.append({"table": table, "status": "error", "message": str(e)})
    
    return results
```

You can use it like this:

```python
# Execute for all tables
results = execute_mappings_by_table(combined_mappings)

# Or for specific tables
# results = execute_mappings_by_table(combined_mappings, ['Student', 'Staff'])
```

how to get all sheet names in excel

##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Here's how to get all sheet names from an Excel file:

```python
def get_excel_sheets(excel_file='esp_data_mod.xlsx'):
    xls = pd.ExcelFile(excel_file)
    return xls.sheet_names
```

Let's try it:

```python
sheets = get_excel_sheets()
print(sheets)
```

Okay, I'm modifying the function to populate the transformation logic and confidence code. I need to pull in a mapping type from the table transformation column, and also from the Excel file mentioned earlier. Regarding the confidence code, I previously had a default value. Now, if it's a conditional mapping, I want to randomly choose a value between 0.8 and 1. Otherwise, if it's a direct mapping, keep the confidence code at 1. So, please modify the function accordingly.


##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Let's modify the function to include the transformation logic and confidence code as requested:

```python
import random

def build_mapping_table(sheet_name='Student'):
    df = pd.read_excel('esp_data_mod.xlsx', sheet_name=sheet_name)
    mapping_df = pd.DataFrame(columns=['TABLENAME', 'TARGET_COLUMN', 'SOURCE_TABLE', 'SOURCE_COLUMN', 
                                      'MAPPING_TYPE', 'TRANSFORMATION', 'CONFIDENCE', 'SOURCE_SIS_TYPE'])
    
    for i, row in df.iterrows():
        eschool = row['Eschool']
        if pd.isna(eschool): continue
        
        # Convert to string if it's not already
        eschool = str(eschool)
            
        # Extract the source table from Eschool field (before the dot)
        source_parts = eschool.split('.')
        source_table = source_parts[0] if len(source_parts) > 0 else eschool
        
        # Extract the source column from Eschool field (after the dot)
        source_column = source_parts[1] if len(source_parts) > 1 else ""
        
        # Check for conditional mapping in upload considerations
        upload_considerations = str(row['Upload Considerations']) if not pd.isna(row['Upload Considerations']) else ""
        
        # Determine mapping type and transformation
        if "if" in upload_considerations.lower() or "when" in upload_considerations.lower() or "=" in upload_considerations:
            mapping_type = 'CONDITIONAL'
            transformation = upload_considerations
            confidence = random.uniform(0.8, 1.0)
        else:
            mapping_type = 'DIRECT'
            transformation = ""
            confidence = 1.0
        
        mapping_df.loc[i] = [
            sheet_name,                  # TABLENAME
            row['PowerSchoolFields'],    # TARGET_COLUMN
            source_table,                # SOURCE_TABLE
            source_column.strip(),       # SOURCE_COLUMN (trimming any whitespace)
            mapping_type,                # MAPPING_TYPE - now dynamic
            transformation,              # TRANSFORMATION - now includes logic when conditional
            confidence,                  # CONFIDENCE - now varies based on mapping type
            'ESP'                        # SOURCE_SIS_TYPE
        ]
    
    return mapping_df
```

Let's test it with the Student sheet:

```python
student_mapping = build_mapping_table('Student')
print(f"Total mappings: {len(student_mapping)}")
print("\nConditional mappings:")
print(student_mapping[student_mapping['MAPPING_TYPE'] == 'CONDITIONAL'].head())
```

I have rename the col Upload Considerations to TRANSFORMATION please modify the code...


##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->

Let's update the code to use the renamed column:

```python
import random

def build_mapping_table(sheet_name='Student'):
    df = pd.read_excel('esp_data_mod.xlsx', sheet_name=sheet_name)
    mapping_df = pd.DataFrame(columns=['TABLENAME', 'TARGET_COLUMN', 'SOURCE_TABLE', 'SOURCE_COLUMN', 
                                      'MAPPING_TYPE', 'TRANSFORMATION', 'CONFIDENCE', 'SOURCE_SIS_TYPE'])
    
    for i, row in df.iterrows():
        eschool = row['Eschool']
        if pd.isna(eschool): continue
        
        # Convert to string if it's not already
        eschool = str(eschool)
            
        # Extract the source table from Eschool field (before the dot)
        source_parts = eschool.split('.')
        source_table = source_parts[0] if len(source_parts) > 0 else eschool
        
        # Extract the source column from Eschool field (after the dot)
        source_column = source_parts[1] if len(source_parts) > 1 else ""
        
        # Check for conditional mapping in TRANSFORMATION column
        transformation_text = str(row['TRANSFORMATION']) if not pd.isna(row['TRANSFORMATION']) else ""
        
        # Determine mapping type and transformation
        if "if" in transformation_text.lower() or "when" in transformation_text.lower() or "=" in transformation_text:
            mapping_type = 'CONDITIONAL'
            transformation = transformation_text
            confidence = random.uniform(0.8, 1.0)
        else:
            mapping_type = 'DIRECT'
            transformation = transformation_text
            confidence = 1.0
        
        mapping_df.loc[i] = [
            sheet_name,                  # TABLENAME
            row['PowerSchoolFields'],    # TARGET_COLUMN
            source_table,                # SOURCE_TABLE
            source_column.strip(),       # SOURCE_COLUMN (trimming any whitespace)
            mapping_type,                # MAPPING_TYPE - now dynamic
            transformation,              # TRANSFORMATION - now includes logic when conditional
            confidence,                  # CONFIDENCE - now varies based on mapping type
            'ESP'                        # SOURCE_SIS_TYPE
        ]
    
    return mapping_df
```

Let's test it:

```python
student_mapping = build_mapping_table('Student')
print(f"Total mappings: {len(student_mapping)}")
print("\nSample of mappings:")
print(student_mapping.head())
```

In [ ]:
import random

def build_mapping_table(sheet_name='Student'):
    df = pd.read_excel('esp_data_mod.xlsx', sheet_name=sheet_name)
    mapping_df = pd.DataFrame(columns=['TABLENAME', 'TARGET_COLUMN', 'SOURCE_TABLE', 'SOURCE_COLUMN', 
                                      'MAPPING_TYPE', 'TRANSFORMATION', 'CONFIDENCE', 'SOURCE_SIS_TYPE'])
    
    for i, row in df.iterrows():
        eschool = row['Eschool']
        if pd.isna(eschool): continue
        
        # Convert to string if it's not already
        eschool = str(eschool)
            
        # Extract the source table from Eschool field (before the dot)
        source_parts = eschool.split('.')
        source_table = source_parts[0] if len(source_parts) > 0 else eschool
        
        # Extract the source column from Eschool field (after the dot)
        source_column = source_parts[1] if len(source_parts) > 1 else ""
        
        # Check for conditional mapping in TRANSFORMATION column
        transformation_text = str(row['TRANSFORMATION']) if not pd.isna(row['TRANSFORMATION']) else ""
        
        # Determine mapping type and transformation
        if "if" in transformation_text.lower() or "when" in transformation_text.lower() or "=" in transformation_text:
            mapping_type = 'CONDITIONAL'
            transformation = transformation_text
            confidence = random.uniform(0.8, 1.0)
        else:
            mapping_type = 'DIRECT'
            transformation = transformation_text
            confidence = 1.0
        
        mapping_df.loc[i] = [
            sheet_name,                  # TABLENAME
            row['PowerSchoolFields'],    # TARGET_COLUMN
            source_table,                # SOURCE_TABLE
            source_column.strip(),       # SOURCE_COLUMN (trimming any whitespace)
            mapping_type,                # MAPPING_TYPE - now dynamic
            transformation,              # TRANSFORMATION - now includes logic when conditional
            confidence,                  # CONFIDENCE - now varies based on mapping type
            'ESP'                        # SOURCE_SIS_TYPE
        ]
    
    return mapping_df

In [ ]:
student_mapping = build_mapping_table('Students')
print(f"Total mappings: {len(student_mapping)}")
print("\nSample of mappings:")
print(student_mapping.head())

Total mappings: 59

Sample of mappings:
  TABLENAME   TARGET_COLUMN  ... CONFIDENCE SOURCE_SIS_TYPE
0  Students  Student_Number  ...   0.806771             ESP
1  Students        SchoolID  ...   0.941337             ESP
2  Students      First_Name  ...   1.000000             ESP
3  Students     Middle_Name  ...   1.000000             ESP
4  Students       Last_Name  ...   1.000000             ESP

[5 rows x 8 columns]

In [ ]:
print(student_mapping.head())

  TABLENAME   TARGET_COLUMN  ... CONFIDENCE SOURCE_SIS_TYPE
0  Students  Student_Number  ...   0.806771             ESP
1  Students        SchoolID  ...   0.941337             ESP
2  Students      First_Name  ...   1.000000             ESP
3  Students     Middle_Name  ...   1.000000             ESP
4  Students       Last_Name  ...   1.000000             ESP

[5 rows x 8 columns]

In [ ]:
def extract_table_names(column_array):
    table_names = set()
    
    for col in column_array:
        if not isinstance(col, str):
            continue
            
        # Split by spaces, newlines and commas to handle multi-line entries
        parts = col.replace('\n', ' ').replace(',', ' ').split()
        
        for part in parts:
            # Look for table.column pattern
            if '.' in part:
                table = part.split('.')[0]
                # Some cleaning to handle edge cases
                table = table.strip("' ")
                if table:
                    table_names.add(table)
    
    return sorted(list(table_names))

def generate_bulk_insert_statement(insert_header,table_names, target_table, source_sis_type="ESP", source_sis_version="sample_tenant_uid_4"):

    # Create each row value
    value_rows = []
    for source_table in table_names:
        value_row = f"('{target_table}', '{source_table}', '{source_sis_type}', '{source_sis_version}')"
        value_rows.append(value_row)
    
    # Join all values with commas and add semicolon at the end
    values_part = ",\n".join(value_rows) + ";"
    
    # Combine header and values
    return insert_header + "\n" + values_part


def execute_sql(sql_statement):
    """
    Execute a SQL statement in Snowflake and return the results.
    Args:
        sql_statement (str): The SQL statement to execute
    Returns:
        list: Results from the query execution
    """
    try:
        # Establish connection to Snowflake
        conn = sf_connection()
        cur = conn.cursor()
        
        # Execute the SQL statement
        cur.execute(sql_statement)
        
        # For SELECT statements, fetch results
        if sql_statement.strip().upper().startswith("SELECT"):
            results = cur.fetchall()
            return results
        else:
            # For INSERT/UPDATE/DELETE statements, return affected row count
            return f"Statement executed successfully. Rows affected: {cur.rowcount}"
            
    except Exception as e:
        return f"Error executing SQL: {str(e)}"
    finally:
        # Close cursor and connection
        if cur:
            cur.close()
        if conn:
            conn.close()